### ISSUE TITLE
Null values in F2 of optimised network

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/NetworkModel_World#14]
/NetworkSetup/Per_Continent/Australia_Oceania/NetwerkSpec/CreateMoreEfficientNetwork/OptimiseNetwork/Iter_2/IntermediateLinkSet/F2 throws 3 null values (after the commit on 14/12, 22:07, SHA 5edc8b510ba51e832c5b5aa6edad2d6220bbd552)

The issue comes into play in the second iteration because a number of JunctionFreeSection ids are not represented in ConnectorLinks/JunctionFreeSection_rel .

Solutions tried:
- Moved entire network and nodeset to Webmercator (hypothesis: to avoid potential issues with WGS84 not being discerning enough geographically)
- Set all OneDirections to False (hypothesis: weird closed-off sections due to haphazard onedirection codes)
Both solutions did not work.

The issue is currently circumvened (after the commit on 15/12. 08:26, SHA 77a05e511e002a6422e0aafeb5751005b91d2509) but the cause is unknown. This merits a deeper look to understand the cause properly.

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/NetworkModel_World/assets/48675272/91645df5-9609-4722-84be-813a7a4f9814)

Indeed now there are no issues

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/NetworkModel_World/assets/48675272/8acee207-c7c5-42e5-b25e-59bc7e938d37)

**Comment by jipclaassens** [comment]
https://github.com/ObjectVision/AccessibilityModelling/wiki/Network-optimisation-algorithm

**Comment by jipclaassens** [comment]
de min(id(connector_link), connector_link/jfs_rel) gaf een undefned getal weer +4.2miljard, of 0 in het geval van max(). Dat is niet goed. Die zijn iig nu vervangen met first en last.

**Comment by jipclaassens** [comment]
Nu denk ie een jfs te zijn, maar geen connector links te hebben.

**Comment by jipclaassens** [comment]
It might be due to unconnected parts in the network. Now added a connectiveness script after creating the initial network. Based on WebMercator. En still a lot of unconnected parts

**Comment by cjacobscrisioni** [comment]
The network is expected to consist of multiple unconnected parts by design - else we would drop all roads in eg Fiji. The rule is to accept small subnetworks if they happen to be the only one connected to a sep_unit (ie an island)

**Comment by jipclaassens** [comment]
Yes, i know. But still with your script there are subnetworks. 

Still investigating, tbc

**Comment by jipclaassens** [comment]
Here, only connected links are selected (based on Chris' script, which takes islands/countries into consideration).
`/NetworkSetup/Per_Continent/Australia_Oceania/NetwerkSpec/CreateInitialWorkingNetwork/Roads_Connected`

Next, the connect-operator is applied.

Then, I calculated the connectedness again on the result. And now there are unconnected links again...

![image](https://github.com/ObjectVision/NetworkModel_World/assets/48675272/c8fcf7a8-332e-43db-86fe-767b8d7b9072)

![image](https://github.com/ObjectVision/NetworkModel_World/assets/48675272/8864b448-7648-4dd3-9660-e4fda5c65789)

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/NetworkModel_World/assets/48675272/022f995d-9b55-4523-8c95-a48126b4376a)


![image](https://github.com/ObjectVision/NetworkModel_World/assets/48675272/3cd3fe65-1349-45a8-ba62-ada3a69659f9)

**Comment by jipclaassens** [comment]
Fixed!

**Comment by cjacobscrisioni** [comment]
ahhhh whahoo congrats !!!!
