### ISSUE TITLE
Catchment area generation causes GeoDMS to crash occasionally.

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/NetworkModel_World#19]
Updating the store_catchment element causes crashes infrequently

Most recently crashed when updating the element for Africa / ATF. Also happened for a country in Australia_Oceania (unsure which). Occurred in ...QT.exe and GeoDMSRun.exe, both version 14.7.0

Not yet verified whether this occurs in specific countries (signalling a false coding assumption) or randomly (signalling something harder to track)

**Comment by cjacobscrisioni** [comment]
ATF: French southern territories. No permanent residents but lots of pinguins. Presumably no settlements, no roads.

**Comment by cjacobscrisioni** [comment]
Issue also occurs in 'Z03' (territory yet unclear)

**Comment by cjacobscrisioni** [comment]
Also occurs in 'MDV' (Maldiven)

**Comment by cjacobscrisioni** [comment]
Idem 'SAU' (Saudi Arabia)

**Comment by cjacobscrisioni** [comment]
Idem 'TKL' (Tokelau, 1411 residents)

**Comment by cjacobscrisioni** [comment]
Idem 'NLD' (Netherlands, small tax haven on the North Sea)

**Comment by cjacobscrisioni** [comment]
Idem 'NOR' (Norway)

**Comment by cjacobscrisioni** [comment]
Idem 'SJM' (Svalbard)

**Comment by cjacobscrisioni** [comment]
Idem 'CAN' (Canada)

**Comment by jipclaassens** [comment]
What exactly does crash?
This?

`/Analyses/Create_Centres_Catchments/Australia_Oceania/Country_Catchments/TKL/all_catchments`

![image](https://github.com/ObjectVision/NetworkModel_World/assets/48675272/05019b60-c47c-4b4e-93a5-b41076c96e95)

**Comment by cjacobscrisioni** [comment]
Crashed when storing during a mass batch operation. 

I plan to look into all issues once the entire process is finished. 

The fact you get results suggests that it's not my coding (huh) but machine specific, or specific to GeoDMS 14.7.0

I will file a request for the most recent GeoDMS version once the dust is settled on Maarten and Erik's point conversion work, I don't want to overburden my admin in Ispra with updates :)

In any case just maybe I can skip the catchment area generation process in case a county has no settlements or hardly any grid cells.

**Comment by cjacobscrisioni** [comment]
GRD (Grenada) caused a crash as well on my machine

note that all countries except the above mentioned went through OK (ran Africa, Asia, Australia and Oceania, Europe, and currently running North America), so it's not all doom and gloom

**Comment by cjacobscrisioni** [comment]
Idem PAN (Panama)

**Comment by cjacobscrisioni** [comment]
Idem CHL (Chile)

**Comment by cjacobscrisioni** [comment]
Idem COL (Colombia)

**Comment by cjacobscrisioni** [comment]
Idem GUF (French Guyana)

**Comment by cjacobscrisioni** [comment]
Z03: China. Lots of settlements and lots of grids (connected and unconnected). Threw an error in batch, but ran without problems from the GUI now. Weird.

MDV runs separately from the GUI as well. Only has one local centre, should include the beforementioned rule so that default to country borders if grids < 100 (tentatively) || #Settlements < 2

Also SAU, TKL, NLD, NOR. GUI then hardcrashed again on SJM (I updated the prior countries without reloading though)

**Comment by cjacobscrisioni** [comment]
SJM causes persistent hard crashes at /Analyses/Create_Centres_Catchments/Europe/Country_Catchments/SJM/Add_Unconnected_Grids/all_grids/dependent_point

Failreason may be the many small sep_units (some may have no grids) maybe in combination with no settlements. SMJ should in any case be exempted by the rule described above.

**Comment by cjacobscrisioni** [comment]
Workaround for now: suppress windows crash error messages as they annoyingly halt the process, then verify later if any files are missing. Windows crash messages are suppressable as in: https://stackoverflow.com/questions/35328567/suppress-error-notification-in-batch-file

**Comment by jipclaassens** [comment]
Svalbard crasht altijd: "application stopt working"

**Comment by jipclaassens** [comment]
> SJM causes persistent hard crashes at /Analyses/Create_Centres_Catchments/Europe/Country_Catchments/SJM/Add_Unconnected_Grids/all_grids/dependent_point
> 
> Failreason may be the many small sep_units (some may have no grids) maybe in combination with no settlements. SMJ should in any case be exempted by the rule described above.

In the GUI, v 14.10.0, is works... 

![image](https://github.com/ObjectVision/NetworkModel_World/assets/48675272/8c2f8465-01f1-4a10-8932-68ba75c41395)

**Comment by cjacobscrisioni** [comment]
Oooh that _is_ positive! As a check, could you reproduce the error in 14.7.0?

**Comment by cjacobscrisioni** [comment]
SJM ran fine with the latest updates and GeoDMS 14.9.0. Case closed.

**Comment by jipclaassens** [comment]
> GeoDMSRun (14.9.0) crashes in EGY, ATF, KEN (Africa), Z03, Z07, IDN, IRN (Asia) after the last updates.

Could it be a result of previously created fss-files? I've just run Kenia without a problem.

**Comment by jipclaassens** [comment]
EGY also works fine at my end...

**Comment by cjacobscrisioni** [comment]
Just pushed the batch files that I use to generate all catchments then FRAs
