### ISSUE TITLE
Thinkthrough needed for countries that are in multiple continents

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/NetworkModel_World#21]
Weird results in Turkey, crash in Russia. 

- Turkey is ran as a country in Asia but the network is in Europe. Straightforward change.
- The network in Russia is split between the European and the Asian part with a slight overlap, but not full overlap. This may need prior editing.

**Comment by cjacobscrisioni** [comment]
Moved Turkey to Europe using the Continents_edit attribute in local_units. See push a30bbee..3459649

**Comment by cjacobscrisioni** [comment]
> Russia is currently considered fully European. The Continents definition boundaries seem to coincide fairly well with the break in OSM networks coverage

Probably best to split Russia in a European and Asian part. This does impose a constraint on catchments and FRAs, but a defendable one.

**Comment by jipclaassens** [comment]
hack verzinnen om een stukje extra rusland toe te voegen?

**Comment by cjacobscrisioni** [comment]
Just pushed a solution - I am now dividing Russia into two parts, with regional units being assigned to Asia or Europe depending on which continental network has the most links in a regional unit. This is a bit slow but the processing data is unlinked from the regional unit generation processes so should be fine (does require recomputation of all the unlinked data though)
