### ISSUE TITLE
Unexpected catchment exceptions

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/NetworkModel_World#26]
List of exceptional situations from this week's catchment area generation run

![image](https://github.com/ObjectVision/NetworkModel_World/assets/144823297/d4e04189-5a8b-4eac-9808-59243159f787)
Canada gets torn (issue with reprojection to Mollweide?)

![image](https://github.com/ObjectVision/NetworkModel_World/assets/144823297/403e097a-110a-418d-9cb3-74041cd0b52e)
Weird patterns close to the Amazon

![image](https://github.com/ObjectVision/NetworkModel_World/assets/144823297/c1cbdf91-1dfd-4bf2-a1ca-d3b5ee8c6f9e)
Asian Russia on the western hemisphere treated as separate from the bits on the eastern hemisphere

**Comment by cjacobscrisioni** [comment]
Canada tear: is already present in /Analyses/Create_Centres_Catchments/North_America/Unconnected_Grids/Geometry_MW so not an issue with the network analysis

**Comment by cjacobscrisioni** [comment]
Amazon weird patterns: seem to be caused by unconnected ferry in the river, maybe best to fix manually at a later stage

**Comment by eoudejans** [comment]
Issue seems related to either artifacts in input data and/or too strict calculation rules in /SourceData/population/sel_LandCells as you mentioned. However if you think it is related to GeoDMS' internal workings, like reprojection, feel free to add either @MaartenHilferink or @eoudejans to the list of assignees.

**Comment by cjacobscrisioni** [comment]
Canada tear fixed, Amazon issue needs fix to source OSM networks or manual adjustment later.
