### ISSUE TITLE
Replace GADM with CIESIN boundaries

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/NetworkModel_World#27]
To be consistent with existing WPP boundaries

Tricky issue: need to cut Russia somehow. Probably manually.

**Comment by cjacobscrisioni** [comment]
Boundary definitions updated in b68adfe8d5ec505c870f145aacf538f6d99706e1

Requires data downloadable here: https://surfdrive.surf.nl/files/index.php/s/rYIHL5qz9oGZF1b

- CIESIN national boundaries, inflated by the JRC-GHSL team
- Dissolved Russian regional boundaries into ARUS and ERUS (Asian and European Russia, respectively). Needs to be in temp folder in the current iteration.

Currently double-checking whether these data may become public domain.

**Comment by jipclaassens** [comment]
The Rus_dissolved.shp does not open. Not sure if i need it, though?

**Comment by cjacobscrisioni** [comment]
CIESIN  boundaries implemented successfully and functional areas generated again. 

CIESIN has OK-ed making these boundaries public domain

@jipclaassens, please let me know if you encountered further issues with the CIESIN boundaries

Will close this issue now.
