### ISSUE TITLE
Merge settlement layers

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/NetworkModel_World#9]

**Comment by cjacobscrisioni** [comment]
... in order to define settlement hierarchies / local and regional centres using the networkmodel_world config. 

Methodology as in https://rsaiconnect.onlinelibrary.wiley.com/doi/abs/10.1111/pirs.12727

**Comment by cjacobscrisioni** [comment]
... ought to be followed by a comparison with mozaiked EU settlement hierarchies.

**Comment by cjacobscrisioni** [comment]
Note - currently integrating 1km grid points immediately in the network definition. Need to revisit the grids later as I will have to vectorize the grids at a late stage.

@jipclaassens my plan is to take the mollweide grid, turn every grid cell into an intermediate union(x4) of the grid corners, reproject the corners to WGS84, and turn the resulting lat/lon grids into a polygon. Just to check, am I missing a more efficient hidden GeoDMS operator to turn grids into vectors?

**Comment by jipclaassens** [comment]
I just discussed this with @MaartenHilferink. He pointed out that he had already proposed a solution to a similar problem for Bas in 2up. You'll get distorted results if you use _connect_ to points in wgs84. He, therefore, added functionality to transform the roads and points to Mercator and connect it there. 

For your case, where you need an approximate 1km grid pointset, you'll also get a distortion towards the poles. Since we need to analyse at a local level, he suggests making horizontal banded study areas, e.g., every 5 degrees. In that way, if you use Mercator, you'll limit the distortion. Also, when using convolution, on the equator, you'll go ten cells west and east and ten cells north and south, whereas in Norway, you'll still go ten cells north and south but 100 cells west and east.

**Comment by cjacobscrisioni** [comment]
Status: work underway. More complicated than anticipated. Ferry routes are typically not encoded in OSM, so that continents with many islands (ie Oceania) typically have many unconnected networks (eg Australia and New Zealand). To ensure that we maintain relevant unconnected networks, I am extending the connected network routine: 1) split mulitpolygons into separate entities; 2) select all roads that are the largest subnetwork from at least one split polygon.

**Comment by cjacobscrisioni** [comment]
Ferries downloaded manually through https://overpass-turbo.eu/ . I will add them as a separate datasource and include them in all  continental networks

**Comment by cjacobscrisioni** [comment]
Settlements merged successfully. Network issues resolved (and off-topic anyway)
